import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "sonner";
import LoginSuccessToast from "@/components/LoginSuccessToast";
import AuthProvider from "@/providers/AuthProvider";
import GoogleMapsProvider from "@/providers/GoogleMapsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <GoogleMapsProvider>
            <AuthProvider>
              {children}
              <LoginSuccessToast />
              <Toaster richColors position="top-right" />
            </AuthProvider>
          </GoogleMapsProvider>


        </QueryProvider>

      </body>
    </html>
  );
}
